apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loan-validator-portal.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loan-validator-portal.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.configMap | nindent 2 }}
