{{- define "loan-validator-portal.configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loan-validator-portal.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "loan-validator-portal.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
