apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: postgres-secret
  data:
{{- range $index, $item := .Values.externalSecrets.secrets }}
{{- if eq $item.name "postgres-secret" }}
{{- range $item.data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.secretStore.awsKey }}
        property: {{ .remoteKey }}
{{- end }}
{{- end }}
{{- end }}
