apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "observability.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "observability.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "observability.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: otel-collector
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - /otelcol-contrib
          - --config=/conf/otel-collector-config.yaml
        ports:
        - containerPort: {{ .Values.service.ports.otlpGrpc }}
          name: otlp-grpc
        - containerPort: {{ .Values.service.ports.otlpHttp }}
          name: otlp-http
        - containerPort: {{ .Values.service.ports.health }}
          name: health
        volumeMounts:
        - name: otel-collector-config
          mountPath: /conf
        - name: tmp
          mountPath: /tmp
        env:
        - name: DATADOG_API_KEY
          valueFrom:
            secretKeyRef:
              name: otel-datadog-secret
              key: DATADOG_API_KEY
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.ports.health }}
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.ports.health }}
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: otel-collector-config
        configMap:
          name: {{ include "observability.fullname" . }}-config
      - name: tmp
        emptyDir: {}