{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: datadog-api-key
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: datadog-api-key
  data:
  {{- range .Values.externalSecrets.secrets }}
    {{- if eq .name "datadog-api-key" }}
    {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecrets.secretStore.name }}/{{ $.remoteRef.key | default "" }}
        property: {{ .remoteKey }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
