apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.government.name }}
  namespace: {{ .Values.externalSecrets.government.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.government.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{- range $k,$v := .Values.externalSecrets.government.secretsMapping }}
        {{ $k }}: "{{ '{{ .' }}{{ $v }} }}"
        {{- end }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.government.awsKey }}
