apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.loan.name }}
  namespace: {{ .Values.externalSecrets.loan.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.loan.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
{{- range $k, $v := .Values.externalSecrets.loan.secretsMapping }}
        {{ $k }}: {{ $v | quote }}
{{- end }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.loan.awsKey }}
