{{- if .Values.externalSecrets.database }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.database.name }}
  namespace: {{ .Values.externalSecrets.database.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecrets.database.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{- range $k, $v := .Values.externalSecrets.database.secretsMapping }}
        {{ $k }}: "{{ $v }}"
        {{- end }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.database.awsKey }}
{{- end }}
