{{- if and .Values.externalSecrets.government .Values.externalSecrets.government.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.government.name }}
  namespace: {{ .Values.externalSecrets.government.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.government.name }}
    creationPolicy: Owner
  data:
{{- range $k, $v := .Values.externalSecrets.government.secretsMapping }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ $.Values.externalSecrets.government.awsKey }}
        property: {{ $v }}
{{- end }}
{{- end }}
