{{- if and .Values.externalSecrets.loan .Values.externalSecrets.loan.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.loan.name }}
  namespace: {{ .Values.externalSecrets.loan.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.externalSecrets.loan.name }}
    creationPolicy: Owner
  data:
{{- range $k, $v := .Values.externalSecrets.loan.secretsMapping }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ $.Values.externalSecrets.loan.awsKey }}
        property: {{ $v }}
{{- end }}
{{- end }}