{{- if and .Values.datadog.externalSecret .Values.datadog.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.datadog.externalSecret.name }}
  namespace: {{ .Values.datadog.externalSecret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name | default "aws-secrets-manager" }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.datadog.externalSecret.name }}
    creationPolicy: Owner
  data:
{{- range $k, $v := .Values.datadog.externalSecret.secretsMapping }}
    - secretKey: {{ $k }}
      remoteRef:
        key: {{ $.Values.datadog.externalSecret.awsKey }}
        property: {{ $v }}
{{- end }}
{{- end }}
