{{- if and .Values.database.externalSecret .Values.database.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.database.externalSecret.name }}
  namespace: {{ .Values.database.externalSecret.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore.name | default "aws-secrets-manager" }}
    kind: SecretStore
  target:
    name: {{ .Values.database.externalSecret.name }}
    creationPolicy: Owner
  data:
    {{- range $k, $v := .Values.database.externalSecret.secretsMapping }}
    {{ $k }}: "{{ $v }}"
    {{- end }}
  dataFrom:
    - extract:
        key: {{ .Values.database.externalSecret.awsKey }}
{{- end }}
