{{- if and .Values.externalSecrets .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.government.name }}
  namespace: {{ .Values.externalSecrets.government.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ .Values.externalSecrets.government.name }}
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{- range $k, $v := .Values.externalSecrets.government.secretsMapping }}
        {{ $k }}: "{{ $v }}"
        {{- end }}
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.government.awsKey }}
{{- end }}
