apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Values.secretStore.namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.awsRegion }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStore.credentialsSecret }}
            key: access-key
          secretAccessKeySecretRef:
            name: {{ .Values.secretStore.credentialsSecret }}
            key: secret-access-key
