apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Add this
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretStore.awsRegion }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: {{ .Values.secretStore.credentialsSecret }}
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: {{ .Values.secretStore.credentialsSecret }}
            namespace: external-secrets
            key: secret-access-key